name: Deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write 
  repository-projects: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ruby-version: 2.7

    steps:
      - uses: actions/checkout@v4
      
      - name: Clone SDK repositories
        run: |
          make clone-sdk-repos

      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.7
        with:
          # Optional output file paths, defaults to '[./README.md]'.
          output_file_paths: '[./source/includes/*.md]'

          # Categories to automatically sync or transform its contents in the markdown files.
          # Defaults to '[code-block,json-to-html-table,workflow-artifact-table]'
          categories: '[code-block,json-to-html-table]'

      - name: Clean SDK repositories
        run: |
          make clean-sdk-repos

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - run: bundle exec middleman build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
